version: "3.9"
services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - "./.dev-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "dev"
      POSTGRES_DB: "dmt_dev"
