[package]
name = "dmt"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license-file.workspace = true

[dependencies]
libdmt = {path = "../libdmt/"}
clap = { version = "4.5", features = ["derive"] }
